import { Project } from '@/types/project';

export const projects: Project[] = [
  {
    slug: 'healthcare-patient-portal',
    title: 'Patient Portal & Telehealth Platform',
    client: 'Community Health Clinic',
    industry: 'healthcare',
    services: ['Custom Software', 'Mobile Apps'],
    year: '2024',
    thumbnail: '/images/projects/healthcare-portal-thumb.jpg',
    hero: '/images/projects/healthcare-portal-hero.jpg',
    description: 'A comprehensive patient portal with telehealth capabilities, appointment booking, and secure messaging for a Montreal community health clinic serving 5,000+ patients.',
    challenge: 'The clinic was using paper records and phone-based appointment booking, leading to long wait times, missed appointments, and frustrated patients. They needed a HIPAA/PHIPA-compliant digital solution but had a limited budget.',
    solution: 'We built a custom web and mobile patient portal with secure login, health record access, appointment booking, prescription refills, and integrated video consultations. The system integrates with their existing EMR through HL7 messaging.',
    results: [
      {
        metric: '40%',
        value: 'Reduction',
        description: 'Decrease in no-show appointments with automated reminders',
      },
      {
        metric: '300+',
        value: 'Virtual Visits',
        description: 'Telehealth consultations in first 3 months',
      },
      {
        metric: '4.8/5',
        value: 'Patient Rating',
        description: 'Average satisfaction score for the portal',
      },
    ],
    technologies: [
      'Next.js',
      'TypeScript',
      'PostgreSQL',
      'WebRTC',
      'Twilio Video',
      'AWS',
    ],
    features: [
      'Secure patient authentication with MFA',
      'Health record viewing and download',
      'Appointment booking and management',
      'Secure messaging with providers',
      'Video consultations (telehealth)',
      'Prescription refill requests',
      'Lab results notifications',
      'Mobile apps (iOS and Android)',
    ],
    testimonial: {
      quote: 'Vinerals delivered a patient portal that would have cost us 3x with a traditional agency. The quality exceeded our expectations and our patients love it.',
      author: 'Dr. Marie Leclerc',
      role: 'Medical Director',
      company: 'Community Health Clinic',
    },
    featured: true,
  },
  {
    slug: 'food-traceability-platform',
    title: 'Farm-to-Fork Traceability System',
    client: 'Regional Organic Cooperative',
    industry: 'food-systems',
    services: ['Custom Software', 'Mobile Apps', 'Data Systems'],
    year: '2024',
    thumbnail: '/images/projects/food-traceability-thumb.jpg',
    hero: '/images/projects/food-traceability-hero.jpg',
    description: 'Supply chain traceability platform connecting 50+ organic farms with distributors and retailers, enabling complete product tracking from farm to consumer.',
    challenge: 'The cooperative needed to meet organic certification requirements and provide traceability for food safety compliance, but members were using paper logs and spreadsheets. When recalls happened, it took days to trace products.',
    solution: 'We developed a mobile-first traceability system with QR code scanning, batch tracking, and automated compliance reporting. Farmers use mobile apps to log harvests, distributors scan products during handling, and retailers can instantly verify origin.',
    results: [
      {
        metric: '50+',
        value: 'Farms Connected',
        description: 'Organic farms using the platform',
      },
      {
        metric: '2 hours',
        value: 'Recall Time',
        description: 'From days to 2 hours for product tracing',
      },
      {
        metric: '100%',
        value: 'Compliance',
        description: 'Organic certification audit pass rate',
      },
    ],
    technologies: [
      'React Native',
      'Node.js',
      'MongoDB',
      'QR Code API',
      'Google Maps',
      'AWS Lambda',
    ],
    features: [
      'Mobile harvest logging (offline-capable)',
      'QR code batch tracking',
      'Supply chain visibility dashboard',
      'Automated compliance reporting',
      'Recall management system',
      'Farmer and distributor portals',
      'Consumer product verification',
      'Geospatial mapping',
    ],
    testimonial: {
      quote: 'This system transformed how we operate. We went from paper chaos to complete traceability in 3 months. The mobile app is so simple that even our oldest farmers use it daily.',
      author: 'Jean-François Dubois',
      role: 'Operations Manager',
      company: 'Regional Organic Cooperative',
    },
    featured: true,
  },
  {
    slug: 'carbon-tracking-dashboard',
    title: 'Carbon Accounting & ESG Reporting Platform',
    client: 'Manufacturing Company',
    industry: 'sustainability',
    services: ['Data Systems', 'Custom Software'],
    year: '2023',
    thumbnail: '/images/projects/carbon-dashboard-thumb.jpg',
    hero: '/images/projects/carbon-dashboard-hero.jpg',
    description: 'Automated carbon footprint tracking system for a mid-size manufacturer, measuring Scope 1, 2, and 3 emissions with real-time ESG dashboards for investors.',
    challenge: 'The company committed to net-zero targets but was tracking emissions in spreadsheets. Annual ESG reports took 2 months of manual work, and investors wanted real-time data. Existing carbon accounting software cost $80K+ per year.',
    solution: 'We built a custom carbon accounting platform that automatically imports utility data, calculates emissions using GHG Protocol methodology, and generates investor-ready ESG reports. The system tracks Scope 1-3 emissions across 5 facilities.',
    results: [
      {
        metric: '95%',
        value: 'Time Saved',
        description: 'Automated ESG reporting vs manual',
      },
      {
        metric: '22%',
        value: 'Reduction',
        description: 'Carbon emissions identified and reduced',
      },
      {
        metric: '$75K',
        value: 'Annual Savings',
        description: 'Avoided subscription costs vs SaaS',
      },
    ],
    technologies: [
      'Python',
      'Django',
      'PostgreSQL',
      'Pandas',
      'Chart.js',
      'Docker',
    ],
    features: [
      'Automated utility data import',
      'GHG Protocol carbon calculations',
      'Scope 1, 2, and 3 tracking',
      'Real-time ESG dashboards',
      'Investor reporting portal',
      'Anomaly detection alerts',
      'Goal tracking and forecasting',
      'Multi-facility management',
    ],
    testimonial: {
      quote: 'We saved over $75,000 per year compared to carbon accounting SaaS products, and got a system tailored exactly to our operations. The ROI was immediate.',
      author: 'Sarah Chen',
      role: 'Sustainability Director',
      company: 'Manufacturing Company',
    },
    featured: true,
  },
  {
    slug: 'cooperative-management-system',
    title: 'Democratic Governance Platform',
    client: 'Worker Cooperative Network',
    industry: 'non-profit',
    services: ['Custom Software'],
    year: '2024',
    thumbnail: '/images/projects/coop-platform-thumb.jpg',
    hero: '/images/projects/coop-platform-hero.jpg',
    description: 'Cooperative management platform for a network of 12 worker co-ops, enabling democratic voting, profit-sharing calculations, and member governance.',
    challenge: 'The network was coordinating governance across 12 co-ops using email, Google Docs, and in-person meetings. Voting took weeks, profit-sharing calculations were error-prone, and new members struggled to understand governance processes.',
    solution: 'We developed a cooperative governance platform with digital voting, automated profit-sharing calculations based on hours worked, proposal management workflows, and member onboarding. The system respects the seven cooperative principles.',
    results: [
      {
        metric: '12',
        value: 'Cooperatives',
        description: 'Co-ops using the platform',
      },
      {
        metric: '3 days',
        value: 'Vote Time',
        description: 'From weeks to 3 days for decisions',
      },
      {
        metric: '100%',
        value: 'Accuracy',
        description: 'Automated profit-sharing calculations',
      },
    ],
    technologies: [
      'Next.js',
      'TypeScript',
      'PostgreSQL',
      'NextAuth.js',
      'Resend',
    ],
    features: [
      'Secure member authentication',
      'Digital voting system',
      'Proposal submission and discussion',
      'Automated profit-sharing calculations',
      'Meeting management and minutes',
      'Member directory and profiles',
      'Document repository',
      'Governance training modules',
    ],
    testimonial: {
      quote: 'As a cooperative building technology for cooperatives, Vinerals understood our needs deeply. This platform embodies cooperative values in every feature.',
      author: 'Marc Tremblay',
      role: 'Network Coordinator',
      company: 'Worker Cooperative Network',
    },
    featured: false,
  },
  {
    slug: 'ai-document-extraction',
    title: 'AI-Powered Invoice Processing',
    client: 'Food Distribution Company',
    industry: 'food-systems',
    services: ['AI Integration', 'Custom Software'],
    year: '2024',
    thumbnail: '/images/projects/ai-invoices-thumb.jpg',
    hero: '/images/projects/ai-invoices-hero.jpg',
    description: 'Automated invoice data extraction system using AI to process 1,000+ supplier invoices per month, reducing manual data entry by 80%.',
    challenge: 'The company was manually entering data from 1,000+ invoices per month into their accounting system. The process took 60+ hours per month, was error-prone, and delayed payment to suppliers.',
    solution: 'We implemented an AI document processing pipeline using OpenAI GPT-4 Vision to extract invoice data (supplier, date, line items, totals), validate against purchase orders, and auto-populate the accounting system. The system handles multiple invoice formats.',
    results: [
      {
        metric: '80%',
        value: 'Time Saved',
        description: 'Reduction in manual data entry',
      },
      {
        metric: '95%',
        value: 'Accuracy',
        description: 'Automated extraction accuracy',
      },
      {
        metric: '$3,200',
        value: 'Monthly Savings',
        description: 'In labor costs vs manual entry',
      },
    ],
    technologies: [
      'Python',
      'OpenAI GPT-4 Vision',
      'FastAPI',
      'PostgreSQL',
      'React',
    ],
    features: [
      'PDF and image invoice upload',
      'AI data extraction (GPT-4 Vision)',
      'Multi-format invoice support',
      'Validation against purchase orders',
      'Human review for low-confidence',
      'Direct accounting system integration',
      'Audit trail and version history',
      'Cost tracking and reporting',
    ],
    testimonial: {
      quote: 'We were skeptical about AI hype, but Vinerals focused on real ROI. The system paid for itself in 4 months and our accounting team loves it.',
      author: 'Philippe Martin',
      role: 'CFO',
      company: 'Food Distribution Company',
    },
    featured: false,
  },
];

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((project) => project.slug === slug);
}

export function getFeaturedProjects(): Project[] {
  return projects.filter((project) => project.featured);
}

export function getProjectsByIndustry(industry: Project['industry']): Project[] {
  return projects.filter((project) => project.industry === industry);
}
